name: build debian package
on: [push]
jobs:
  build-debian-package:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Install build dependencies
        run: sudo apt-get -qq update
      - run: sudo apt-get install python3.8 python3.8-dev python3-pip libcurl4 build-essential python3-tornado python3-setuptools debhelper dh-systemd cdbs dh-python fakeroot python3-pip rsync locales
      - run: pip3 install virtualenv
      - name: ğŸ— Create virtual python env
        run: virtualenv -p /usr/bin/python3.8 hotspot-env
      - name: ğŸ— Activate virtual python env
        run: source hotspot-env/bin/activate
      - name: â¬‡ Checkout code
        uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - name: check if push was tagged
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: |
          CURRENT_DATE=$(date +%Y%m%d%H%M) \
          VERSION=$(head -1 debian/changelog | awk -F'[()]' '{print $2}') \
          sed -i -e 's/'"$VERSION"'/'"$VERSION"'+'"$CURRENT_DATE"'/g' debian/changelog
      - name: ğŸ”¨ Build Debian package
        run: sudo make deb
